all: 01 02 03 04 05 06 07

01: 01-wheres-my-parent.cpp
	g++ -std=c++11 01-wheres-my-parent.cpp -o 01.out
	./01.out

02: 02-protected-vs-private.cpp
	g++ -std=c++11 02-protected-vs-private.cpp -o 02.out
	./02.out

03: 03-the-diamond-problem.cpp
	g++ -std=c++11 03-the-diamond-problem.cpp -o 03.out
	./03.out

04: 04-overpowered-rpg-character.cpp
	g++ -std=c++11 04-overpowered-rpg-character.cpp -o 04.out
	./04.out

05: 05-composition-vs-inheritance.cpp
	g++ -std=c++11 05-composition-vs-inheritance.cpp -o 05.out
	./05.out

06: 06-virtual-functions.cpp
	g++ -std=c++11 06-virtual-functions.cpp -o 06.out
	./06.out

07: 07-sneak-peek-polymorphism.cpp
	g++ -std=c++11 07-sneak-peek-polymorphism.cpp -o 07.out
	./07.out

clean:
	rm *.out
